# This is a basic workflow to help you get started with Actions

name: .exe compiler

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  release:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install module
        run: Install-Module ps2exe

      # Runs a set of commands using the runners shell
      - name: Compile
        run:   Invoke-ps2exe .\Runtime ToolboxGUI WIP.ps1 .\Runtime ToolboxGUI WIP.exe
        
       - name: Release Build
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Runtime ToolboxGUI WIP.exe
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
